### ISSUE TITLE
Inaccurate benchmarks results (Skein)

### ISSUE THREAD

**Issue by TomaszDom** [nemosminer/NemosMiner-v2.3#124]
Benchmark results are completely different each time I run them for Skein, sometimes 330, sometimes 1660, now 648, but look at the real speed (8*1060 6GB):

![obraz](https://user-images.githubusercontent.com/9348532/34379702-d2410174-eafc-11e7-9efa-19451b6d22a2.png)

I think the Skein benchmark is too short and/or reads wrong values. I'm using NemosMiner-v2.3c-beta and -SelGPUDSTM '0 1 2 3 4 5 6 7' -SelGPUCC '0,1,2,3,4,5,6,7' on miningpoolhub.

**Comment by TomaszDom** [comment]
I had to run the benchmarks 5 times to make the results accurate.

**Comment by TomaszDom** [comment]
Is the hashrate dependant on current difficulty or is the miner reporting the hashrate all over the place?

**Comment by trhightree** [comment]
I concur. I have 8*1070ti's and Skein takes ~5 minutes to reach 5500 mh/s. Since the benchmark only lasts 2 minutes it's reported as 620 or 1240 mh/s. I manually changed it to 5500 in the benchmark results but now this brings a new issue. The miner has been switching between Lyra2z and Skein quite often, when it switches to Skein I'm losing 30-70% hashrate the first 5 minutes each time.

**Comment by GillyTheGhillie2** [comment]
Run the benchmark for longer by upping the interval in the batch file, really you should be doing this on multi-GPU rigs anyway.

**Comment by kevharper** [comment]
How long would you recommend the interval be for a 4 GPU 1070 rig?

**Comment by thericeking** [comment]
@GillyTheGhillie2 Can you give me an example of how to up the interval in the batch file for more accurate results as you advice for people running multiple GPU rigs? Thank you.

**Comment by thericeking** [comment]
@TomaszDom How can you tell the benchmark is accurate or not?
