### ISSUE TITLE
Error contacting pool, retrying..

### ISSUE THREAD

**Issue by D-TAU** [nemosminer/NemosMiner-v2.3#137]
This issue reproduces periodically during start **startzpool24hr.bat**
startzpool.bat works properly.

Version: NemosMiner-v2.3c-beta
![issue](https://user-images.githubusercontent.com/12089507/34537034-c8bf57e4-f0cf-11e7-9ee3-944f9c56b311.png)

**Comment by nemosminer** [comment]
THANKS I'LL DO SOME TESTING AND SORT IT OUT

**Comment by JhonJhonny** [comment]
@nemosminer i got this issue even with the starzpool.bat
![fgvhnfghfgj](https://user-images.githubusercontent.com/30692674/34614364-860bb7c2-f231-11e7-87a9-83088ec3155c.png)
btw its not a the start, it happened randomly and this is the second time, the first time that happen after 2 or 3 min it goes back normal by itself.
altough it continue mining the algo it's on but i believe it doesn't switch anymore

**Comment by jagauthier** [comment]
It could be zpool not responding, I've seen it's API do that.

**Comment by charnet3d** [comment]
Hi,

I'm having the exact problem with the 24h script. Sometimes it works the first time then stops after that indefinitely. The normal .bat file works flawlessly.

I tried editing the normal zpool file just by exchanging estimate_last24h and estimate_current by actual_last24h but just doing this makes the request return nothing from zpool. Also tried different things like importing Invoke-RestMethod line from MPM and removing -Headers but didn't change anything..

Can you see what could be done for this ? For info the 24h_actual works for me in MPM (when I edit the zpool file)

Thank you.

**Comment by jebidia** [comment]
Same as above.   The 24hr Ahash works flawlessly, zpool 24hr is very hit or miss with the same error reported above.

**Comment by charnet3d** [comment]
I did try ahashpool24h but the x17 miner kept trying to connect for several minutes with no result. The same thing happened to me some days ago which made me sick with zpool but with the estimate version only.

I chose to stay with Nemos because of the better display, benchmarking and the better miners which gave me improved hashrates over the ones in MPM (10.2Mh/s vs 7.5Mh/s on x17).

I guess while waiting for a fix I'll try migrating the miners on MPM and getting the 24h version to run with it.

**Comment by lunatis** [comment]
Im having the exact same issue. It connects fine with the normal zpool, but the 24hr one fails constantly and when it manages to connect, during the mining and the interval time comes, it wont switch if needed because it keeps failing on connecting to the pool. Ahash works flawlessly with both normal and 24hr.
