### ISSUE TITLE
12gup setting for this miner

### ISSUE THREAD

**Issue by ashokthakkar** [nemosminer/NemosMiner-v2.3#165]
how i can add 12gpu in setting? this software support 12gpu(1050ti or 1070)

**Comment by margusvoll** [comment]
I would go even further.
If os sees gpus is there any limit?

I plan to build 16 or 24 gpu setups and wonder if they can be used.

**Comment by Dobromir-Atanasov** [comment]
There is a problem with ccminer-alexis78 when there are over 10 GPU. 11, 12 and so on are ignored and instead miner makes two instances for gpu 0, 1 and so on. Had to reduce my asrock H110 Pro BTC+ rigs from 12 to 10 gpu because of that issue.

**Comment by lunatis** [comment]
There is a way to correct this and it works with 12 GPU as im running the Asrock H110 with 12 GTX 1070ti

On nemosminer foder, go to folder Miners and edit the file .PS1 for each of the miners you are using and As an exemple ill use the ccmineralexis78.ps1 and the delete the following line as ill show in the next example for the X17 algo:

ISSUE:   "x17" = " -i 21 -d $SelGPUCC" #X17
FIX:       "x17" = " -i 21" #17     (leave the space between the " and 1)

and lets say you also have an algo that doesn't use -i (intensity) on the line like the following example this is how you fix it:
ISSUE:   "lyra2v2" = " -d $SelGPUCC" #Lyra2RE2
FIX:       "lyra2v2" = "" #Lyra2RE2

The -d command apparently causes an issue when you have more than 10 cards and this is how i got all my cards to run.

from the batch file that starts the miner, you can also delete this:

-SelGPUDSTM '0 1 2' -SelGPUCC '0,1,2'

I hope this helps you guys because i had an hard time to figure this out and i found a user with the same issue but didn't quite explained it very well on how to resolve it.

Happy mining!
T

**Comment by margusvoll** [comment]
Thanks!
