### ISSUE TITLE
Very long miner "warming up" time

### ISSUE THREAD

**Issue by Olegik-ah** [nemosminer/NemosMiner-v2.3#94]
Hello!
First - sorry for my bad English.
I'am trying v2.2.2 and v2.3 (downloaded from master) - same result.
I have some nvidia rigs. Now i'am testing your software on one rig 6x1070 on zpool. All works perfect. But i have some problems with Alexis78 and Alexis78cuda9 miner. Some algos seems to have very long "warming up" time. What does it mean? When miner starts - it using not all available GPUs (1 or 2). Some time later it starts to use all GPUs. And this "some time" is more than 2 minutes on some algos. Problem algos for 1070 is: blakecoin, hsr, keccak, myr0gr, nist5, poly. If i wait more time 5+ minutes (setting -interval 300) - miner starts to use all GPUs. But 2-4 minutes my rig have no profit on these algos. Please have a look on attachment - Afterburner GPU load
![keccak](https://user-images.githubusercontent.com/31293967/34127019-9f938d8e-e44c-11e7-81cc-7f2299a40969.png)
There are no errors in system eventlog (no driver crash).

Other algos works fine for me.
If i use another miner for these algos - all works fine too. For example: comment keccak algo in CcminerAlexis78cuda9.ps1 and uncomment keccak in CcminerTpruvotcuda9.ps1 - all works perfect! And i have no "warming up" time - mining starts immediately on all GPUs.

I think it is Alexis78 and Alexis78cuda9 miner bugs. Maybe you will replace miners for these algos in future versions?
PS: Win10x64, driver 388.31, CPU G4400

**Comment by Olegik-ah** [comment]
For 1080 skein algo is buggy too.

**Comment by nemosminer** [comment]
thanks

**Comment by wakrather** [comment]
I found with minor clock adjustment of 10mhz, your program is super stable. The increase in hashrate compared to other programs in immense. Please do not change that. Your program rocks.

**Comment by srvsrv** [comment]
The problem is still here. It's only with Alexis bug! Is there any solution?

**Comment by Olegik-ah** [comment]
new "ccminerpoly" is buggy too. As i know - all alexis forks on some algos has wery long startups... Possible fixes:
1. Replase miner.... But alexis is fastest miner... You will have slow hasing.
2. Decrease intensity (-i param of ccminer). For example if you start miner without -i param - it will use default intensity, whitch will showing when miner starts. All algos have different default intensity. For example default intensity for some algo is 31. Try to add -i 29. This tweak will cause little decrease hashing, but speed will good.

PS: sorry for my english:)

**Comment by srvsrv** [comment]
I tried with i parameter, but it seems to work good with i < 20 which down the hashrate to 50%! that not good.. Only possible solution that i found is to replace all algos which use Alexis with CCMiner 2.2.4, seems to work till now! Alexis have very good  hashrate, but for algos switching is not good when you have more than 2-3 gpu's.. i have another rig with only 3 gpu's and there is working good, but if i add another 3 gpu's there.. it have same long startup.. i thing the bug is when there are more gpu's.. i can't find why..

**Comment by Olegik-ah** [comment]
which algo you have try?
For my rig 6x1070:
skein -i 22 (alexis78)
blake2s -i 30 (tpruvot-ccminer gives same resul as alexis78)
I dont remember whitch tweaks i have made more...

**Comment by srvsrv** [comment]
i have 6x1070
Blake2s -i 29 tpruvot-ccminer (same result as Alexis78 but.. some strange things happened when mining)

i have another rig with same 1070 but 3x.. there is no problem with long startups.. i think that bug is caused when there are more than 3/4 GPU's..

I tried to make 2 miners 3x3 GPUS, and it's working with 6 cards, but 2 miners with 3 cards.. just make another .bat and separate cards in to another start.bat

**Comment by srvsrv** [comment]
OK, my solutions to separate 3x3 GPU's in 2 bat files working till now.. no more problem with Alexis long startup.

start1.bat
-SelGPUDSTM '0 1 2' -SelGPUCC '0,1,2'

start2.bat
-SelGPUDSTM '3 4 5' -SelGPUCC '3,4,5'

**Comment by Olegik-ah** [comment]
Thanks for solution! i'll try!
